name: rpi-tig

services:
  influxdb:
    image: influxdb:2
    hostname: influxdb
    container_name: influxdb
    restart: always
  #  mem_limit: 192m
  # Those ports don't need to be exposed to the local host, only
  # Telegraf/grafana are talking to it.
  #  ports:
  #    - "8083:8083"
  #    - "8086:8086"
  #    - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      - ./influxdb/data:/var/lib/influxdb2
      # Configuration
      - ./influxdb/config:/etc/influxdb2

  telegraf:
    image: telegraf:1.30
    hostname: telegraf
    container_name: telegraf
    restart: always
    environment:
    - HOST_PROC=/host/proc
    privileged: true
  #  mem_limit: 384m
    ports:
      # Expose Statsd UDP server to local host
      - "8125:8125/udp"
    links:
      - influxdb
    volumes:
      - ./collectd_types.db:/tmp/collectd_types.db:ro
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
      - /var/log:/host/var/log:ro

  grafana:
    image: grafana/grafana:10.2.6
    hostname: grafana
    container_name: grafana
    restart: always
  #  mem_limit: 384m
    ports:
      - "3000:3000"
    env_file:
      # This is influxdb on purpose, because the variables are used in the provisioning file
      # in grafana/provisioining/datasources
      - 'env.influxdb'
    links:
      - influxdb
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
