# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Telegraf
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: Telegraf
  type: influxdb
  access: proxy
  orgId: 1
  url: http://influxdb:8086/
  basicAuth: false
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     dbName: $DOCKER_INFLUXDB_INIT_BUCKET
     httpHeaderName1: 'Authorization'
     httpMode: POST
  # <string> json object of data that will be encrypted.
  secureJsonData:
     httpHeaderValue1: "Token $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true
